config/routes.rb
Rails.application.routes.draw do

  namespace :api ,defaults: {format: 'json'}do
    namespace :v1 do
      resources :users, only: [:create,:show,:update,:destroy]
      resources :teams, only: [:index,:create,:show,:update,:destroy]
      resources :games, only: [:index,:create,:show,:update,:destroy]
      resources :tokens, only: [:create]
    end
  end

  root 'users#welcome'
  get 'strava_auth' , to: 'users#strava_auth'
  resources :users do
    resources :games
  end
  resources :teams

  resources :team_chats, only: [:new, :create]
  resources :trash_talks, only: [:new, :create]

  get 'logout' , to: 'logout#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :team
  has_many	 :team_chats
  has_many 	 :activities
  has_many   :trash_talks
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ApplicationController

      include StravaPull

      respond_to :json

      def create
        @user = User.create(user_params)
        respond_with @user do |format|
          format.json { render json: @user.to_json }
        end
      end

      def show
        user = User.find(params[:id])
        respond_with get_strava_athlete(user.token)
      end

      def update
        respond_with User.update(params[:id], user_params)
      end

      def destroy
        respond_with User.destroy(params[:id])
      end

      private

      def user_params
        p params
        params.require(:user).permit(:strava_name,:team_id,:token,:refreshtoken)
      end
    end
  end
end

app/controllers/users_controller.rb
require 'httparty'
require 'uri'
class UsersController < ApplicationController
  def welcome
     render :welcome
  end
  # def stravacallback
  #   # p params
  #   @code=params["code"];
  #   redirect_to  strava_auth
  # end
  def strava_auth
    @code=params["code"];
     @response_temp=HTTParty.post("https://www.strava.com/oauth/token",:body=>{
    :client_id => ENV['CLIENT_ID'],
    :client_secret => ENV['CLIENT_SECRET'],
    :code=>@code
    }.to_json,
    :headers => {'Content-Type'=>'application/json'})
    p @response_temp
    access_token=@response_temp.parsed_response["access_token"]
    @user=User.find_by_token(access_token)
    if !@user
    # @user=User.find_or_create_by(:token=>access_token)
      @user= User.new
      p @user.token          = @response_temp.parsed_response["access_token"]
      p @user.strava_id      = @response_temp.parsed_response["athlete"]["id"]
      p @user.firstname      = @response_temp.parsed_response["athlete"]["firstname"]
      p @user.lastname       = @response_temp.parsed_response["athlete"]["lastname"]
      p @user.email          = @response_temp.parsed_response["athlete"]["email"]
      p @user.city           = @response_temp.parsed_response["athlete"]["city"]
      p @user.state          = @response_temp.parsed_response["athlete"]["state"]
      p @user.sex            = @response_temp.parsed_response["athlete"]["sex"]
      p @user.profile_img    = @response_temp.parsed_response["athlete"]["profile"]
      @user.save
    end
    session[:current_user_id] = @user.id
    p session[:current_user_id]
    redirect_to action: "show", id:@user.id
  end
  def index
    render :index
  end

  def show
    @user = User.find(session[:current_user_id])

    if @user.team
      @team = @user.team
      @all_team_members = @team.users
      @teammates = @team.users.where.not(:id=> @user[:id])

      @team_chats = []
      @all_team_members.each do |person|
        person.team_chats.each do |chat|
          @team_chats << chat
        end
      end
      @team_chats = @team_chats.sort_by { |chat| chat.updated_at }.reverse!
    end



    render :show


    # Logic to pull the strava api
    # Find user and get the game through the team
    # if they are not registered with the team then pull only user data
    # if they are not registered with a game pull only the teams data
    # get 8 users id and token into array
    # pull one by one
    # if the user dont have an activity then create one
    # else get the id of the last activity from db get the
    # activity table  activityid and check if it incoming response/(s) id
    # is greater than activiy id



    #if the user does not have a team pull only the user data from Strava
    now=Date.today
    p week_start_unix = now.at_beginning_of_week.to_time.to_i
    google_uri_builder = 'https://maps.googleapis.com/maps/api/staticmap?size=600x600&sensor=false&path=enc:'

    if (!@user.team)
      user_strava_data=HTTParty.get("https://www.strava.com/api/v3/athlete/activities", headers: {"Authorization" => "Bearer #{@user.token}"},query: {:after => week_start_unix})
      p @user.activities.count
      if (@user.activities.count==0)
          user_strava_data.each do |active|
            # p "ere"
            # p @user.activities
            # p active
            act= @user.activities.new
            # p @user.activities.last.activityid
            # p  active["id"]
            if  active["id"]>@user.activities.last.activityid
              act.activityid= active["id"]
              act.user_id= @user.id
              act.map_polyline= URI.escape(google_uri_builder + active["map"]["summary_polyline"] + "&key=#{ENV['GOOGLEAPI']}")
              act.distance= active["distance"]
              act.save
            end
            p @user.activities.last
          end
      else
         p user_strava_data
          user_strava_data.each do |active|
            p "in the else before the user act. count"
             p @user.activities.count
               if (active["id"]>@user.activities.last.activityid )
                 @user.activities.create(activityid: active["id"] ,user_id: @user.id,map_polyline: URI.escape(google_uri_builder + active["map"]["summary_polyline"] + "&key=#{ENV['GOOGLEAPI']}"), distance: active["distance"])
               end
          end
        end

    end

    # if the user does have a team but does not in a game

    # u=User.find(params[:id])

    # t=u.team.games.pluck(:team_id,:awayteam_id)
    # users=[]
    # t.flatten.each { |tid|  users << Team.find(tid).users }
    # tokens=[]
    # users.each { |user | tokens << user.pluck(:token,:id)}

    # p tokens
    # tokens.each do |token|
    #   token.each do |item|
    #  tempm=HTTParty.get("https://www.strava.com/api/v3/athlete/activities", headers: {"Authorization" => "Bearer #{item[0]}"},query: {:after => week_start_unix})
    #   tempm.parsed_response.each do | active|
    #     user=User.find(item[1])
    #     p "acitivyt id "
    #     user.activities
    #     p user.activities.last.activityid
    #     lat= user.activities.last
    #     if (lat==nil)
    #       user.activities.create(activityid: active["id"] ,user_id: user.id,map_polyline: active["map"]["summary_polyline"], distance: active["distance"])
    #     end
    #     if (active["id"]>lat.activityid )
    #        user.activities.create(activityid: active["id"] ,user_id: user.id,map_polyline: active["map"]["summary_polyline"], distance: active["distance"])
    #        end
    #       end
    #     end
    #   p "here"
    # end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def total_distance(user)
    return 0 if user.activities.length == 0

    activities = user.activities.map { |activity| activity.distance }
    activities.reduce(:+)
  end

  def total_distance_team(user_array)
    return 0 if user_array.length == 0

    totals = []
    user_array.each do |user|
      totals << total_distance(user)
    end
    totals.reduce(:+)
  end
end

app/views/users/_team_chat_template.html.erb
<li id="team_chat_template">
  <div class="commenterImage">
    <img src="#" />
  </div>
  <div class="commentText">
    <p class="green_font">#</p><span class="date sub-text green_font">#</span>
  </div>
</li>

app/views/users/_user_sidebar.html.erb
<div class="col-md-4 user_information">
  <img src="<%=@user.profile_img%>" alt="" class="img-circle profile_picture">
  <h4><%=@user.firstname%> <%=@user.lastname%></h4>
  <h4><%=@user.email%></h4>
  <hr>
  <h5><%= total_distance(@user) %> meters run</h5>  <!-- not implemented -->
  <h5><%=@user.city%>, <%=@user.state%></h5>
  <br>
  <a href="/logout"><button type="button" class="btn btn-default">Log Out</button></a>
</div>

app/views/users/index.html.erb
<%= render 'layouts/header'  %>

<div class="non_nav">

  <div class="row">

    <div class="col-md-4 user_information">
      <img src="<%=@user.picture%>" alt="" class="img-circle profile_picture">
      <h3><%=%></h3>
      <h4><%=@user.firstname%> <%=@user.lastname%></h4>
      <h4><%=@user.email%></h4>
      <hr>
      <h5><%=%> miles run</h5>
      <h5><%=@user.city%>, <%=@user.state%></h5>
      <br>
      <a href="/logout"><button type="button" class="btn btn-default">Log Out</button></a>
    </div>



  </div> <!-- non nav -->

app/views/users/show.html.erb
<%= render 'layouts/header'  %>

<div class="non_nav">

  <div class="row">
    <%= render 'user_sidebar' %>

    <% if @user.team %>
      <div class="col-md-8 team_information">
        <h1><%=@team.name%></h1>
        <h3><%=@team.description%></h3>
        <div class="row">

          <% @teammates.each do |teammate| %>
          <div class="col-md-4">
            <img src="<%=teammate.profile_img%>" alt="" class="img-circle team_picture">
            <div>
              <h6><%=teammate.strava_name%></h6>
              <h6><%=teammate.firstname%> <%=teammate.lastname%></h6>
              <h6><%=total_distance(teammate) %> meters run</h6> <!-- not implemented -->
            </div>
          </div>
          <% end %>

        <div class="team_stats">
          <p><%= total_distance_team(@all_team_members) %> total meters run || <%=@team.total_wins%> - <%=@team.total_losses%> record</p> <!-- not implemented -->
          </div>
          <div class="team_messages">
          </div>

          <div class="team_chat_wrapper">

            <div class="title_box">
              <label>Team Chat</label>
            </div>
            <div class="actionBox">


          <%= form_for :team_chat, url: team_chats_path, remote: true,  html: { id: "chat",:'data-type' => 'json'} do |f| %>

            <%= f.text_field :content, :class=>"form-control", :placeholder => "chat" %>
            <%= f.hidden_field :user_id, :value => @user.id %>
          <% end %>




          <!--     <form id="team_chat_form" class="form-inline" role="form" accept-charset="UTF-8" action="/team_chats" method="post">
                <div class="form-group">
                  <input id="article_title" class="form-control" name="team_chats[content]" type="text" />
                </div>
                <div class="form-group">
                  <input name="commit" type="submit" value="Create" class="btn btn-default" />
                </div>
              </form> -->

              <ul id="team_chat_target" class="commentList">
                <% @team_chats.each do |chat| %>
                <li>
                  <div class="commenterImage">
                    <img src="<%=chat.user.profile_img%>" />
                  </div>
                  <div class="commentText">
                    <p class="green_font"><%=chat.content%></p> <span class="date sub-text"><%=chat.updated_at%></span>

                  </div>
                </li>

                <%end%>


                <%= render 'team_chat_template' %>
              </ul>
            </div>
          </div>
        </div>
      </div>

    <% else %>
      <div class="col-md-8 no_team">
        <div class="no_team_content">
          <h3>No team selected</h3>
          <br>
          <a href="/teams"><button type="button" class="btn btn-success">Explore Teams <i class="fa fa-search"></i> </button></a>
        </div>
      </div>

    <% end %>

  </div> <!-- non nav -->

</div>

app/views/users/welcome.html.erb
<!DOCTYPE html>
<html lang="en">
<head>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--   <link rel="stylesheet" href="css/normalize.css">
  <link rel="stylesheet" href="css/bootstrap.min.css">
  <link rel="stylesheet" href="css/application.css"> -->

  <title></title>
</head>
<body>

  <!-- Navigation -->
  <a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-thumbs-up"></i></a>

  <nav id="sidebar-wrapper">
    <ul class="sidebar-nav">
      <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-thumbs-up"></i></a>
      <li class="sidebar-brand">About</li>
      <li>StraVS. is a competitive biking and running application built using the Strava API. Users sign in with an exisiting Strava account and form teams with their friends or peers. Teams challenge eachother to week-long battles of endurance and athletics. A winner is determined at the end of the week by summing the total distance run by each team.</li>
      <li>Visit our github page to learn more:<br><br>
      <div><a href="https://github.com/muratdbc/strava"><%=image_tag("github.png", class: "github_image")%></a></li></div>
    </ul>
  </nav>

  <!-- Header -->
  <header id="top" class="splash">
    <div class="text-vertical-center">
      <h1>straVS.</h1>
      <h3>Form teams. Work out. Win bragging rights.</h3>
      <br>
      <a id=""href="https://www.strava.com/oauth/authorize?client_id=3744&response_type=code&redirect_uri=http://localhost:3000/strava_auth&approval_prompt=auto"><%=image_tag("strava_connect.png")%></a>
    </div>
  </header>


</body>

<!-- <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="js/bootstrap.js"></script>
<script src="js/application.js"></script> -->

<script>
    // Closes the sidebar menu
    $("#menu-close").click(function(e) {
      e.preventDefault();
      $("#sidebar-wrapper").toggleClass("active");
    });

    // Opens the sidebar menu
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#sidebar-wrapper").toggleClass("active");
    });

    // $("")


    </script>





    </html>